#!/bin/sh
### BEGIN INIT INFO
# Provides:          opbk
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start opbk at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    echo "Starting opbk"
    /bin/bash -c '/home/ow_py_mysqlbackup/ow_py_mysqlbackupenv/bin/python3 /home/ow_py_mysqlbackup/src/backup_mysql.py > output.log 2>&1 &' &
    ;;
  stop)
    echo "Stopping opbk"
    pkill -f /home/ow_py_mysqlbackup/src/backup_mysql.py
    ;;
  *)
    echo "Usage: /etc/init.d/opbk {start|stop}"
    exit 1
    ;;
esac

exit 0
